#FIBONACCI THREAD

import threading
class FibonacciThread(threading.Thread):
    def __init__(self, n, result):
        super().__init__()
        self.n=n
        self.result=result

    def run(self):
        a,b=0,1
        for _ in range(self.n):
            self.result.append(a)
            a,b=b,a+b


#MAIN THREAD
if __name__=="__main__":
    n_terms=12
    fib_results=[]

#CREATE AND START A THREAD TO GENERATE FIBONACCI NUMBERS
     
    fib_thread=FibonacciThread(n_terms,fib_results)
    fib_thread.start()

#WAIT FOR THE THREAD TO COMPLETE

    fib_thread.join()

    print("Fibonacci Sequence generated By Thread",fib_results)
